server:
  port: 8082
  servlet:
    context-path: /rightplatform
  error:
    whitelabel:
      enabled: false

businessAddress: 192.168.3.233

spring:
  application:
    name: G-RightPlatform
  main:
    allow-bean-definition-overriding: false
  redis:
    host: ${businessAddress}
    password: 12345678
    database: 0
    jedis:
      pool:
        max-active: 8
        min-idle: 4
        max-wait: 5000
        max-idle: 16
  jackson:
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    name: ${spring.application.name}
    url: jdbc:mysql://${businessAddress}:3306/go189right?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
  cloud:
    nacos:
      discovery:
        port: ${server.port}
        username: nacos
        password: nacos
        service: ${spring.application.name}
        metadata:
          schema: http
          version: 1.0.0
          context: ${server.servlet.context-path}
        namespace: public
        group: public
        server-addr: ${businessAddress}:8848


dubbo:
  application:
    registry: nacos://${businessAddress}:8848
    name: rightplatform
  protocol:
    name: dubbo
  scan:
    base-packages: com.chinatelecom.interface5g.user
  registry:
    address: nacos://${businessAddress}:8848
    group: dubbo
    dynamic: true
    username: nacos
    password: nacos

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.chinatelecom.rightplatform.model

project:
  info:
    domain: 192.168.3.130
    cookie: D5D7444F3FFFF1C688F481E50E03BDB96C6F21EA9FE0EE89
    g5domain: http://${businessAddress}:9999/g5
    url: http://192.168.3.130/
